language: nix
script: nix-build

before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo "binary-caches = https://nixcache.reflex-frp.org https://cache.nixos.org/" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo "binary-cache-public-keys = ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" | sudo tee -a /etc/nix/nix.conf > /dev/null
